### ISSUE TITLE
Any tips on training a good model ?

### ISSUE THREAD

**Issue by akikaaa** [bitextor/bicleaner#26]
Hi, thanks for such a good project. I trained a model on 5 million sentence paires extracted from UN parallel corpus with almost all default settings and tested on a private dataset. I found that except nearly half of the sentence pair scores are 0, all other sentence pairs' scores are closely around 0.5, and the score order doesn't well match the ture order in human sense. So I'm wondering how to train a good model?

**Comment by mbanon** [comment]
Hi @akikaaa ,
I'm glad you find Bicleaner useful, thank you so much!

Regarding your issue, did you read our recently published Wiki page on  training Bicleaner?  
https://github.com/bitextor/bicleaner/wiki/How-to-train-your-Bicleaner
I strongly suggest you to read it , because it contains some of our 'expertise', and you'll surely find it useful.

You did not provide much information, but some likely causes of the low scores:

* You are training a language pair that is not "safe" to identify with pycld2. In this case, you should use the  `--disable_lang_ident` flag (and version 0.13, which has not been released yet but you can find it in a branch: it provides a stronger 'disable language identification' feature than 0.12 (current master))

* The low scores might be caused by a not too clean training corpus.  Since you have a training corpus of 5million sentences and 100K are enough to get nice training results, you can try using only the cleanest part of your 5 milion sentences. For that,  you can use Bifixer and the Hardrules tool, as explained here https://github.com/bitextor/bicleaner/wiki/How-to-train-your-Bicleaner#training-corpus 

* The '0 scores' might be caused by the Hardrules or by the Language Model. I'll suggest to run the  Hardrules with the `--annotated_output`. For this, you should use version 0.13 because it  has the  Language Model filtering integrated into the Hardrules, and it will be easier to identify what is causing the 0 scores.  You can learn which hardrules are causing your 0 scores by running:
`cat corpus.annotated | awk -F'\t' '{print $4}' | sort | uniq -c | sort -nr` on the annotated output of the Hardrules.

I hope some of these suggestions helps you. Please let me know if you are still experiencing issues.

-Marta

**Comment by akikaaa** [comment]
Hi @mbanon ,
Thanks for your response. I followed your suggestions to run the Hardrules with the --annotated_output and found same of the hardrule regex does not work well for my target language so I disabled it. I also reduce the number of input sentences. The result became much better.

**Comment by mbanon** [comment]
@akikaaa  Great! I'm glad to read that it helped :)
